### ISSUE TITLE
think through how to subsection tips

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/tracing-guides#15]
subsections on tips (ala lxbarth roads tips)
1 -> 1a, etc

process to bring multiple tips on several tips together

**Comment by wuhland** [comment]
This is coming to a head with our Karrangetang guide. It is looking loco right now and think grouping tips are a necessity to get it to work. It would be good to make a new guide layout that puts all the tips you group together under one heading with in-page navigation elements generated only for the tip-groups. This is essentially what you suggested Mikel just putting it here for documentation (I think this is the right place). I can try to take a stab at it over the weekend, I need to learn liquid templating better anyways.

**Comment by d3netxer** [comment]
cool man, In my guide I am doing a bunch of Africa road tips. They can all be grouped together.

**Comment by mikelmaron** [comment]
David

Design wise, would it work to add to the current layout, horizontal bars across the width of the page, with the name of each section?

Mikel

**Comment by wuhland** [comment]
Yea I think the current guide mostly works, a slight edit so that grouped
tips are under one heading and have one background color enforce their
groupedness would be the ticket. Also having navigation elements point to
the group headings. Now that you mention it editing the current layout
makes allot of sense compared to making a new one.

**Comment by wuhland** [comment]
Having some trouble with how to structure the YAML. At first I thought the way forward was a sequence with mappings mixed in like so:

```
tips:
 -tip
 -tip
 - Group1:
  - tip
  - tip 
  - tip
 - Group2:
  - tip
  - tip
  - tip
```

But apparently that is proper and I got an error message saying it couldnt be parsed. 

This seemed to work: 

```
tips:
 -tip
 -tip
 - 
  - tip
  - tip 
  - tip
 - 
  - tip
  - tip
  - tip
```

But its not obvious how to group the tips under one heading. Anybody have any ideas on a way forward?

**Comment by mikelmaron** [comment]
David, I actually haven't implemented a different structure yet, so not surprised you got an error.The yaml is valid, there just isn't a layout to handle it yet.
Should we finish this up on Tuesday? 

```
 On Sunday, March 22, 2015 6:56 PM, David Saeger <notifications@github.com> wrote:
```

 Having some trouble with how to structure the YAML. At first I thought the way forward was a sequence with mappings mixed in like so:tips:
 -tip
 -tip
- Group1:
  - tip
  - tip 
  - tip
- Group2:
  - tip
  - tip
  - tip
    But apparently that is proper and I got an error message saying it couldnt be parsed. This seemed to work: tips:
    -tip
    -tip
- 
  - tip
  - tip 
  - tip
- 
  - tip
  - tip
  - tip
    But its not obvious how to group the tips under one heading. Anybody have any ideas on a way forward?—

**Comment by wuhland** [comment]
That would be great! I gave making a new structure a shot but didn't get
very far. Would be nice to take a look at where I went wrong on Tuesday,

On Sun, Mar 22, 2015 at 6:59 PM, Mikel Maron notifications@github.com
wrote:

> David, I actually haven't implemented a different structure yet, so not
> surprised you got an error.The yaml is valid, there just isn't a layout to
> handle it yet.
> Should we finish this up on Tuesday?
> 
> On Sunday, March 22, 2015 6:56 PM, David Saeger notifications@github.com
> wrote:
> 
> Having some trouble with how to structure the YAML. At first I thought the
> way forward was a sequence with mappings mixed in like so:tips:
> -tip
> -tip
> - Group1:
> - tip
> - tip
> - tip
> - Group2:
> - tip
> - tip
> - tip
>   But apparently that is proper and I got an error message saying it couldnt
>   be parsed. This seemed to work: tips:
>   -tip
>   -tip
>   -
> - tip
> - tip
> 
> ## \- tip
> - tip
> - tip
> - tip
>   But its not obvious how to group the tips under one heading. Anybody have
>   any ideas on a way forward?—
> 
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hotosm/tracing-guides/issues/15#issuecomment-84728973
> .

## 

David Saeger
202-802-6382

**Comment by d3netxer** [comment]
You can also try something like this.   -Tom

```
---
title: River Cress and Grand Gedeh Counties
subtitle: Liberia
category: Guide
layout: guide3
banner: https://cloud.githubusercontent.com/assets/2665840/6713865/6f8c06fc-cd6b-11e4-97b2-247dc26ca2e0.jpg
footer: https://donatenow.networkforgood.org/static-resources/skin/12214/graphics/logo.jpg
tips:
  - gettingstarted brightness settings 2
  - id alignment vector
groups:
  - group1:
      title: roads
      tips: [classifying roads in africa, tertiary roads, residential roads, tracks, unclassified roads, paths]
---
```
