### ISSUE TITLE
Enable Guide 3 to have image in footer that has a link

### ISSUE THREAD

**Issue by d3netxer** [hotosm/tracing-guides#66]
I added this to the footer2.html include file. This should work now with the guide 3 layout. Here is an example of how you would write it in the YAML:

```
footer: 
  - image:
       src: https://cloud.githubusercontent.com/assets/2665840/11611337/2ca01dca-9b96-11e5-95f0-153e0811a897.png
       link: http://mapgive.state.gov/
```
